name: Deploy Markdown to GitHub Pages

on:
  push:
    branches:
      - main  # Esegui il workflow quando viene fatto push al branch main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install markdown

    - name: List Markdown files
      run: find . -name '*.md'

    - name: Convert Markdown to HTML
      run: |
        mkdir -p ./articles
        python convert_md_to_html.py

    - name: List output directory
      run: ls -la articles

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: main
        publish_dir: ./articles
